fx_version 'cerulean'
game 'gta5'
description 'An advanced logging system for FiveM.'
version '1.0.0'
author 'Boppe'
lua54 'yes'

client_script 'client/main.lua'
server_script 'server/main.lua'
shared_script 'shared/config.lua'